# LAB | Implementation of Graphs



## Overview



This lesson will cover the implementation of graphs in Python, focusing on two primary representations: adjacency list and adjacency matrix. We will also explore operations such as insertion and deletion of nodes and edges, as well as searching and traversing the graph.



## Instructions



- Complete each section by understanding the concepts and implementing the provided code.
- Test your code to ensure it behaves as expected.



## A. Graph Representation Using Adjacency List



In this section, we will implement a graph using an adjacency list. This representation uses a dictionary where keys are vertices and values are lists of adjacent vertices.



### Key Concepts



- **Vertex**: A node in the graph.
- **Edge**: A connection between two vertices.



### Implementation Steps

1. Create a class `Graph` that contains a dictionary to represent the adjacency list.
2. Implement methods to add and remove vertices and edges.


### Explanation
This cell demonstrates the implementation. Take a moment to check out the code and run the cell to see how it works.

In [ ]:
class Graph:
    def __init__(self):
        self.graph = {}

    def add_vertex(self, vertex):
        if vertex not in self.graph:
            self.graph[vertex] = []

    def remove_vertex(self, vertex):
        if vertex in self.graph:
            del self.graph[vertex]
            for v in self.graph:
                if vertex in self.graph[v]:
                    self.graph[v].remove(vertex)

    def add_edge(self, vertex1, vertex2):
        if vertex1 in self.graph and vertex2 in self.graph:
            self.graph[vertex1].append(vertex2)
            self.graph[vertex2].append(vertex1)  # For undirected graph

    def remove_edge(self, vertex1, vertex2):
        if vertex1 in self.graph and vertex2 in self.graph:
            self.graph[vertex1].remove(vertex2)
            self.graph[vertex2].remove(vertex1)  # For undirected graph


In [3]:
# Example usage:
g = Graph()
g.add_vertex(1)
g.add_vertex(2)
g.add_edge(1, 2)
g.remove_edge(1, 2)

### Try It Yourself!
Modify the implementation below or try writing your own version based on what you've learned above.

In [29]:
class Graph:
    def __init__(self) -> None:
        self.graph = {}

    def add_vertex(self, vertex):
        # if the vertex doesn't exist:
        if vertex not in self.graph:
            # create vertex/Node without content
            self.graph[vertex]= []

    def remove_vertex(self, vertex):
        # remove the vertex itsself
        del self.graph[vertex]
        # remove all edges from other vetices
        for v in self.graph:
            if vertex in self.graph[v]:
                self.graph[v].remove(vertex)

    def add_edge(self, vertex1, vertex2):
        if vertex1 in self.graph and vertex2 in self.graph:
            self.graph[vertex1].append(vertex2)
            self.graph[vertex2].append(vertex1)
    
    def remove_edge(self, vertex1, vertex2):
        if vertex1 in self.graph and vertex2 in self.graph:
            self.graph[vertex1].remove(vertex2)
            self.graph[vertex2].remove(vertex1)

    def print_graph(self):
        for vertex in self.graph:
            print(f"{vertex}: {self.graph[vertex]}")
        
g = Graph()
g.add_vertex(1)
g.add_vertex("adsgf") 
g.remove_vertex("adsgf") 
g.add_vertex("Test1") 
g.add_vertex("Test2") 
g.add_vertex("Test3") 
g.add_edge("Test1", "Test2")
g.add_edge("Test2", "Test3")
g.print_graph()
print("------------------------")
g.remove_vertex("Test2") 
g.print_graph()
g.remove_vertex("Test1") 
g.remove_vertex("Test3") 
print("------------------------")
g.add_vertex(1)
g.add_vertex(2)
g.add_edge(1, 2)
g.print_graph()
print("------------------------")
g.remove_edge(1, 2)
g.print_graph()

1: []
Test1: ['Test2']
Test2: ['Test1', 'Test3']
Test3: ['Test2']
------------------------
1: []
Test1: []
Test3: []
------------------------
1: [2]
2: [1]
------------------------
1: []
2: []



## B. Graph Representation Using Adjacency Matrix



In this section, we will implement a graph using an adjacency matrix. This representation uses a 2D list (matrix) where rows and columns represent vertices.



### Key Concepts

- **Adjacency Matrix**: A square matrix used to represent a finite graph.



### Implementation Steps

1. Create a class `GraphMatrix` that initializes a matrix based on the number of vertices.
2. Implement methods to add and remove vertices and edges.


### Explanation
This cell demonstrates the implementation. Take a moment to check out the code and run the cell to see how it works.

In [30]:
class GraphMatrix:
    def __init__(self, size):
        self.size = size
        self.matrix = [ [0] * size for _ in range(size)]

    def add_edge(self, vertex1, vertex2):
        if 0 <= vertex1 < self.size and 0 <= vertex2 < self.size:
            self.matrix[vertex1][vertex2] = 1
            self.matrix[vertex2][vertex1] = 1  # For undirected graph

    def remove_edge(self, vertex1, vertex2):
        if 0 <= vertex1 < self.size and 0 <= vertex2 < self.size:
            self.matrix[vertex1][vertex2] = 0
            self.matrix[vertex2][vertex1] = 0  # For undirected graph

In [31]:
# Example usage:
g_matrix = GraphMatrix(3)
g_matrix.add_edge(0, 1)
g_matrix.remove_edge(0, 1)

### Try It Yourself!
Modify the implementation below or try writing your own version based on what you've learned above.

In [38]:
import numpy as np

class GraphMatrix:
    def __init__(self, size) -> None:
        self.size = size
        self.matrix = np.zeros((size, size), dtype=int)

    def add_edge(self, vertex1, vertex2):
        # test if vertices are out of bound:
        if 0 <= vertex1 < self.size and 0 <= vertex2 <= self.size:            
            self.matrix[vertex1][vertex2] = 1
            self.matrix[vertex2][vertex1] = 1

    def remove_edge(self, vertex1, vertex2):
        # test if vertices are out of bound:
        if 0 <= vertex1 < self.size and 0 <= vertex2 <= self.size:
            self.matrix[vertex1][vertex2] = 0
            self.matrix[vertex2][vertex1] = 0

    def print_matrix(self):
        print(self.matrix)

g_matrix = GraphMatrix(3)
g_matrix.add_edge(0, 1)
g_matrix.print_matrix()
print("------------------------")
g_matrix.remove_edge(0, 1)
g_matrix.print_matrix()
print("------------------------")

[[0 1 0]
 [1 0 0]
 [0 0 0]]
------------------------
[[0 0 0]
 [0 0 0]
 [0 0 0]]
------------------------


### Operations on Adjacency List
 

### Explanation
Below cells demonstrate the implementation. Take a moment to check out the code and run the cells to see how it works.


#### Add Vertex

This operation adds a new vertex to the graph.


In [5]:
def add_vertex(self, vertex):
    if vertex not in self.graph:
        self.graph[vertex] = []

### Try It Yourself!
Modify the implementation below or try writing your own version based on what you've learned above.

In [ ]:
class Graph:
    def __init__(self) -> None:
        self.graph = {}

    def add_vertex(self, vertex):
        # if the vertex doesn't exist:
        if vertex not in self.graph:
            # create vertex/Node without content
            self.graph[vertex]= []

    def print_graph(self):
        for vertex in self.graph:
            print(f"{vertex}: {self.graph[vertex]}")


#### Remove Vertex

This operation removes a vertex from the graph along with its associated edges.


In [6]:
def remove_vertex(self, vertex):
    if vertex in self.graph:
        del self.graph[vertex]
        for v in self.graph:
            if vertex in self.graph[v]:
                self.graph[v].remove(vertex)


### Try It Yourself!
Modify the implementation below or try writing your own version based on what you've learned above.

In [ ]:
class Graph:
    def __init__(self) -> None:
        self.graph = {}

    def remove_vertex(self, vertex):
        # remove the vertex itsself
        del self.graph[vertex]
        # remove all edges from other vetices
        for v in self.graph:
            if vertex in self.graph[v]:
                self.graph[v].remove(vertex)   

    def print_graph(self):
        for vertex in self.graph:
            print(f"{vertex}: {self.graph[vertex]}")


#### Add Edge

This operation adds an edge between two vertices.


In [7]:
def add_edge(self, vertex1, vertex2):
    if vertex1 in self.graph and vertex2 in self.graph:
        self.graph[vertex1].append(vertex2)
        self.graph[vertex2].append(vertex1)  # For undirected graph



### Try It Yourself!
Modify the implementation below or try writing your own version based on what you've learned above.

In [ ]:
class Graph:
    def __init__(self) -> None:
        self.graph = {}

    def add_edge(self, vertex1, vertex2):
        if vertex1 in self.graph and vertex2 in self.graph:
            self.graph[vertex1].append(vertex2)
            self.graph[vertex2].append(vertex1)
    
    def print_graph(self):
        for vertex in self.graph:
            print(f"{vertex}: {self.graph[vertex]}")


#### Remove Edge

This operation removes an edge between two vertices.


In [8]:
def remove_edge(self, vertex1, vertex2):
    if vertex1 in self.graph and vertex2 in self.graph:
        self.graph[vertex1].remove(vertex2)
        self.graph[vertex2].remove(vertex1)  # For undirected graph



### Try It Yourself!
Modify the implementation below or try writing your own version based on what you've learned above.

In [40]:
class Graph:
    def __init__(self) -> None:
        self.graph = {}

    def remove_edge(self, vertex1, vertex2):
        if vertex1 in self.graph and vertex2 in self.graph:
            self.graph[vertex1].remove(vertex2)
            self.graph[vertex2].remove(vertex1)

    def print_graph(self):
        for vertex in self.graph:
            print(f"{vertex}: {self.graph[vertex]}")


### Example Usage for Adjacency List


In [47]:
class Graph:
    def __init__(self) -> None:
        self.graph = {}

    def add_vertex(self, vertex):
        # if the vertex doesn't exist:
        if vertex not in self.graph:
            # create vertex/Node without content
            self.graph[vertex]= []

    def remove_vertex(self, vertex):
        # remove the vertex itsself
        del self.graph[vertex]
        # remove all edges from other vetices
        for v in self.graph:
            if vertex in self.graph[v]:
                self.graph[v].remove(vertex)

    def add_edge(self, vertex1, vertex2):
        if vertex1 in self.graph and vertex2 in self.graph:
            self.graph[vertex1].append(vertex2)
            self.graph[vertex2].append(vertex1)
    
    def remove_edge(self, vertex1, vertex2):
        if vertex1 in self.graph and vertex2 in self.graph:
            self.graph[vertex1].remove(vertex2)
            self.graph[vertex2].remove(vertex1)

    def print_graph(self):
        for vertex in self.graph:
            print(f"{vertex}: {self.graph[vertex]}")



g = Graph()

g.add_vertex(1)
g.add_vertex(2)
g.print_graph()
print("-----------------------")
g.add_edge(1, 2)
g.print_graph()
print("-----------------------")
g.remove_edge(1, 2)
g.print_graph()
print("-----------------------")
g.remove_vertex(1)
g.print_graph()

1: []
2: []
-----------------------
1: [2]
2: [1]
-----------------------
1: []
2: []
-----------------------
2: []


### Operations on Adjacency Matrix



#### Add Edge

This operation adds an edge between two vertices in the adjacency matrix.


In [10]:
def add_edge(self, vertex1, vertex2):
    if 0 <= vertex1 < self.size and 0 <= vertex2 < self.size:
        self.matrix[vertex1][vertex2] = 1
        self.matrix[vertex2][vertex1] = 1  # For undirected graph

### Try It Yourself!
Modify the implementation below or try writing your own version based on what you've learned above.

In [48]:
import numpy as np

class GraphMatrix:
    def __init__(self, size) -> None:
        self.size = size
        self.matrix = np.zeros((size, size), dtype=int)

    def add_edge(self, vertex1, vertex2):
        # test if vertices are out of bound:
        if 0 <= vertex1 < self.size and 0 <= vertex2 <= self.size:            
            self.matrix[vertex1][vertex2] = 1
            self.matrix[vertex2][vertex1] = 1


    def print_matrix(self):
        print(self.matrix)



#### Remove Edge

This operation removes an edge between two vertices in the adjacency matrix.


In [11]:
def remove_edge(self, vertex1, vertex2):
    if 0 <= vertex1 < self.size and 0 <= vertex2 < self.size:
        self.matrix[vertex1][vertex2] = 0
        self.matrix[vertex2][vertex1] = 0  # For undirected graph

### Try It Yourself!
Modify the implementation below or try writing your own version based on what you've learned above.

In [ ]:
import numpy as np

class GraphMatrix:
    def __init__(self, size) -> None:
        self.size = size
        self.matrix = np.zeros((size, size), dtype=int)

    def remove_edge(self, vertex1, vertex2):
        # test if vertices are out of bound:
        if 0 <= vertex1 < self.size and 0 <= vertex2 <= self.size:
            self.matrix[vertex1][vertex2] = 0
            self.matrix[vertex2][vertex1] = 0

    def print_matrix(self):
        print(self.matrix)



### Example Usage for Adjacency Matrix


In [49]:
import numpy as np

class GraphMatrix:
    def __init__(self, size) -> None:
        self.size = size
        self.matrix = np.zeros((size, size), dtype=int)

    def add_edge(self, vertex1, vertex2):
        # test if vertices are out of bound:
        if 0 <= vertex1 < self.size and 0 <= vertex2 <= self.size:            
            self.matrix[vertex1][vertex2] = 1
            self.matrix[vertex2][vertex1] = 1

    def remove_edge(self, vertex1, vertex2):
        # test if vertices are out of bound:
        if 0 <= vertex1 < self.size and 0 <= vertex2 <= self.size:
            self.matrix[vertex1][vertex2] = 0
            self.matrix[vertex2][vertex1] = 0

    def print_matrix(self):
        print(self.matrix)



g_matrix = GraphMatrix(3)
g_matrix.add_edge(0, 1)
g_matrix.remove_edge(0, 1)


## Exercise Completion



Once you have completed all sections:

- Review your implementations.
- Ensure your code is well-documented with comments explaining your logic.
- Save your notebook for submission or further review.



Happy coding! Enjoy practicing Graph implementations in Python!

